package com.ecommerce_project.product_service.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

@Entity //This Java class represents a database table named "categories" and defines the structure of the table, including its columns and relationships with other tables. It uses JPA annotations to specify how the class should be mapped to the database.
@Table(name = "categories")
@Getter //This annotation generates getter methods for all fields in the class, allowing you to access the values of the fields.
@Setter //This annotation generates setter methods for all fields in the class, allowing you to modify the values of the fields.
@NoArgsConstructor //creates empty constructor new Category()
@AllArgsConstructor //creates constructor with all fields new Category(Long categoryId, Category parent, List<Category> children, String name, String slug)
public class Category {

    @Id //primary key of the table
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Database auto-increment for categoryId
    @Column(name = "category_id") //coloumn name in the database
    private Long categoryId; //unique identifier for each category, automatically generated by the database.

    @JsonIgnore //This annotation prevents the parent category from being included in the JSON representation of the category, which helps to avoid circular references when serializing the category object to JSON.
    @ManyToOne //many children belongs to one parent category
    @JoinColumn(name = "parent_id")
    private Category parent;

    @Column(name = "parent_id", insertable = false, updatable = false)
    private Long parentId;

    @OneToMany(mappedBy = "parent", cascade = CascadeType.ALL)  //One object can contain many objects.  //mappedBy = "parent" indicates that the "parent" field in the Category class is the owner of the relationship, and cascade = CascadeType.ALL means that any operations (like persist, merge, remove) performed on a parent category will also be applied to its child categories.
    private List<Category> children; //This category stores multiple child category objects in a list, representing the hierarchical structure of categories.

    @Column(name = "name", length = 100, nullable = false)
    private String name;

    @Column(name = "slug", length = 120, unique = true, nullable = false)
    private String slug;
}