# ─── Server ───────────────────────────────────────────
server.port=8083

# ─── App Name ─────────────────────────────────────────
spring.application.name=admin-service

# ─── Other Service URLs ───────────────────────────────
user.service.url=https://e-commerce-website-user-service.onrender.com
product.service.url=https://e-commerce-website-620c.onrender.com

# ─── JWT ──────────────────────────────────────────────
jwt.secret=${JWT_SECRET}

# ─── Swagger ──────────────────────────────────────────
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html